sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - 1.9.4

os:
  - linux
  - osx

env:
  matrix:
    - TARGETS="check"
    - TARGETS="testsuite"

  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"

addons:
  apt:
    packages:
      - python-virtualenv

install:
  - true

script:
  - make $TARGETS

after_success:

