[[override]]
  name = "github.com/rcrowley/go-metrics"
  revision = "972ba8f8e0ceca48c4cd302acdc069cc338930ca"

[[constraint]]
  name = "github.com/elastic/beats"
  version = "6.4.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.18.0"

[[constraint]]
  name = "github.com/bsm/sarama-cluster"
  version = "2.1.15"
