kafkabeat:
  brokers: ["localhost:9092"]
  topics: ["watch"]
  client_id: "beat"
  group: "kafkabeat"
  offset: "newest"
  codec: "plain"
  channel_buffer_size: 1024
  channel_workers: 2

output.elasticsearch:
  enabled: true
  hosts: ["localhost:9200"]

# Set to false to disable template loading.
setup.template.enabled: false
